use_frameworks!

target 'DPPageControl_Example' do
  pod 'DPPageControl', :path => '../'

  target 'DPPageControl_Tests' do
    inherit! :search_paths

#    pod 'Quick'
#    pod 'Nimble'
#    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
  end
end
